### ISSUE TITLE
Confirm licensing

### ISSUE THREAD

**Issue by maxerickson** [maxerickson/michigantownships#1]
Need to determine both whether township borders are usable and to what extent Michigan Geographic Framework is usable.

**Comment by LivInTheLookingGlass** [comment]
An alternate data source would be GNIS, I think. I know that they have some of the townships on there, anyhow. For instance, [Negaunee Township](https://geonames.usgs.gov/apex/f?p=138:3:0::NO::P3_FID,P3_TITLE:1626791,Township%20of%20Negaunee)

**Comment by maxerickson** [comment]
A search in gnis for name 'Township' and class 'civil' returns ~1240 results so it looks like they are all there.

It'd be ideal to import the boundaries from the state, I think they are more accurate than the existing county borders and it would give 100% coverage for geographic searches.

The data from gnis can be added to the import though. I guess I'm not inclined to add place nodes like exist for cities and towns, but the data can be added to the boundaries.

**Comment by LivInTheLookingGlass** [comment]
At the very least it wouldn't hurt to add a GNIS id to the boundaries and whatnot

**Comment by maxerickson** [comment]
I found a contact form on the website and sent a message.

The code checked in right now adds the gnis id and also wikidata and wikipedia tags. The biggest outstanding issue is that the border geometries aren't shared.

**Comment by LivInTheLookingGlass** [comment]
Hey, has anything come of this? If not, is there anything I can do to help? I know a city commissioner that might be able to get things escalated if that would be helpful.

**Comment by maxerickson** [comment]
I heard back, they basically pointed me at the metadata link on the open data site:

https://www.arcgis.com/home/item.html?id=0a4035a25683430284bae0637b7e464c

Which doesn't really speak to redistributing the data. I expect it would be fine to use it, but I'm not sure that will be enough to convince the OSM people that worry over licenses.

**Comment by maxerickson** [comment]
I've traced the boundaries from USGS topo maps, which anyway seem to be more reliable, so closing this.
